import { MdOutlineKeyboardArrowRight } from "react-icons/md";

import { Button } from "@/components/ui/button";


export default function Home() {
  return (
    <main className="rounded-2xl text-white bg-primary my-8 mx-4 py-16 px-12 flex flex-col justify-center items-center">
      <h2 className="text-2xl xl:text-6xl xl:max-w-[60%] text-center font-light mb-4">
        Master any subject with <br/>AI-Powered Flashcards
      </h2>
      <h3 className="text-base xl:max-w-[60%] text-center font-light text-cardBackgroundPrimary">
        Transform your learning experience with personalized flashcards generated by advanced AI. Study smarter, retain more, and achieve your goals.
      </h3>
      <div className="flex flex-col gap-4 xl:flex-row my-8">
        <Button>Get started <MdOutlineKeyboardArrowRight className="text-2xl ml-2" /></Button>
        <Button variant="outline" className="text-white">Try for free</Button>
      </div>
    </main>
  );
}
